--REVOGA-REVOKE

--IDENTIFICA QUAL O USUARIO:
select CURRENT_USER

-- SETAR O BANCO DE DADOS:
USE curso

--REVOGANDO Acesso DE ATUALIZACAO UsrTeste.
REVOKE UPDATE ON FUNCIONARIOS TO UsrTeste; 

-- REVOGANDO Acesso DE inserção UsrTeste.
REVOKE INSERT ON FUNCIONARIOS TO UsrTeste; 

-- REVOGANDO Acesso DE Leitura UsrTeste.
REVOKE SELECT ON FUNCIONARIOS TO UsrTeste; 

--REVOGA DIREITO DE EXECUCAO DA PROC TESTE_PROC PARA UsrTeste.
REVOKE EXECUTE ON testproc TO UsrTeste  

--VERIFICANDO USUARIO LOGADO
select CURRENT_USER


--ALTERANDO USUARIO LOGADO:
SETUSER 'UsrTeste'

--SE DER ERRO, REVOKE E DEPOIS GRANT CONFORME LINHAS ABAIXO:
EXEC sp_revokedbaccess 'UsrTeste'
EXEC sp_grantdbaccess 'UsrTeste','UsrTeste'

SETUSER 'UsrTeste'
--VERIFICANDO USUARIO LOGADO
select CURRENT_USER


--COMO EU REMOVI AS PERMISSÕES DO USUÁRIO, OS COMANDOS ABAIXO NÃO FUNCIONARÃO:
--EXECUTANDO PROCEDURE COM USUARIO UsrTeste
EXEC testproc

--TESTANDO SELECT
SELECT  * from FUNCIONARIOS

--TESTANDO INSERT
INSERT into FUNCIONARIOS values ('Maria','1000','TI')

--TESTANDO UPDATE
UPDATE FUNCIONARIOS set nome='Marilia'
where id='4'

--TESTANDO DELETE
DELETE FROM FUNCIONARIOS
WHERE ID='4'

